//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxonomia_App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaxonomiaEntities : DbContext
    {
        public TaxonomiaEntities()
            : base("name=TaxonomiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Color_prim> Color_prim { get; set; }
        public virtual DbSet<Color_sec> Color_sec { get; set; }
        public virtual DbSet<Division> Division { get; set; }
        public virtual DbSet<Familia> Familia { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<SKU> SKU { get; set; }
        public virtual DbSet<Talla> Talla { get; set; }
    }
}
